API_SIGNATURES = {
    "rsa.generate_private_key": {
        "algorithm": "RSA",
        "category": "asymmetric",
        "library": "cryptography",
        "api": "rsa.generate_private_key",
        "usage": "Key Generation",
        "confidence": 0.99,
        "detection_method": "api_signature",
    },
    "RSA.generate": {
        "algorithm": "RSA",
        "category": "asymmetric",
        "library": "PyCryptodome",
        "api": "RSA.generate",
        "usage": "Key Generation",
        "confidence": 0.98,
        "detection_method": "api_signature",
    },
    "ec.generate_private_key": {
        "algorithm": "ECDSA",
        "category": "digital_signature",
        "library": "cryptography",
        "api": "ec.generate_private_key",
        "usage": "Key Generation",
        "confidence": 0.99,
        "detection_method": "api_signature",
    },
    "ec.ECDSA": {
        "algorithm": "ECDSA",
        "category": "digital_signature",
        "library": "cryptography",
        "api": "ec.ECDSA",
        "usage": "Digital Signature",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
    "hashlib.sha256": {
        "algorithm": "SHA-256",
        "category": "hashing",
        "library": "hashlib",
        "api": "hashlib.sha256",
        "usage": "Hashing",
        "confidence": 0.99,
        "detection_method": "api_signature",
    },
    "hashlib.sha1": {
        "algorithm": "SHA-1",
        "category": "hashing",
        "library": "hashlib",
        "api": "hashlib.sha1",
        "usage": "Hashing",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
    "PBKDF2HMAC": {
        "algorithm": "PBKDF2",
        "category": "password_derivation",
        "library": "cryptography",
        "api": "PBKDF2HMAC",
        "usage": "Password Derivation",
        "confidence": 0.99,
        "detection_method": "api_signature",
    },
    "AES.new": {
        "algorithm": "AES",
        "category": "symmetric_encryption",
        "library": "cryptography",
        "api": "AES.new",
        "usage": "Encryption",
        "confidence": 0.97,
        "detection_method": "api_signature",
    },
    "Cipher(algorithms.AES": {
        "algorithm": "AES",
        "category": "symmetric_encryption",
        "library": "cryptography",
        "api": "Cipher(algorithms.AES",
        "usage": "Encryption",
        "confidence": 0.97,
        "detection_method": "api_signature",
    },
    "createCipheriv": {
        "algorithm": "AES",
        "category": "symmetric_encryption",
        "library": "crypto",
        "api": "createCipheriv",
        "usage": "Encryption",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
    "createDecipheriv": {
        "algorithm": "AES",
        "category": "symmetric_encryption",
        "library": "crypto",
        "api": "createDecipheriv",
        "usage": "Decryption",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
    "createHash": {
        "algorithm": "SHA",
        "category": "hashing",
        "library": "crypto",
        "api": "createHash",
        "usage": "Hashing",
        "confidence": 0.94,
        "detection_method": "api_signature",
    },
    "createHmac": {
        "algorithm": "HMAC-SHA256",
        "category": "authentication",
        "library": "crypto",
        "api": "createHmac",
        "usage": "Authentication",
        "confidence": 0.94,
        "detection_method": "api_signature",
    },
    "Signature.getInstance": {
        "algorithm": "RSA",
        "category": "digital_signature",
        "library": "java.security",
        "api": "Signature.getInstance",
        "usage": "Digital Signature",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
    "Cipher.getInstance": {
        "algorithm": "AES",
        "category": "symmetric_encryption",
        "library": "javax.crypto",
        "api": "Cipher.getInstance",
        "usage": "Encryption",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
    "KeyPairGenerator.getInstance": {
        "algorithm": "RSA",
        "category": "asymmetric",
        "library": "java.security",
        "api": "KeyPairGenerator.getInstance",
        "usage": "Key Generation",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
    "MessageDigest.getInstance": {
        "algorithm": "SHA",
        "category": "hashing",
        "library": "java.security",
        "api": "MessageDigest.getInstance",
        "usage": "Hashing",
        "confidence": 0.96,
        "detection_method": "api_signature",
    },
}
