"""Canonical cryptographic signature metadata and algorithm aliases."""

SIGNATURE_DATABASE = {
    "AES-128-GCM": {
        "algorithm": "AES",
        "canonical_name": "AES-128-GCM",
        "aliases": {"AES-128-GCM", "A128GCM", "AES128GCM", "aes-128-gcm"},
        "category": "symmetric_encryption",
        "library": "unknown",
        "api_patterns": ("AES.new", "Cipher(algorithms.AES", "createCipheriv", "Cipher.getInstance(\"AES/GCM"),
        "quantum_status": "relatively_resistant",
        "risk_default": "LOW",
        "pqc_recommendation": "Monitor key management and preferred modes; continue to validate scheme assumptions.",
    },
    "AES-192-GCM": {
        "algorithm": "AES",
        "canonical_name": "AES-192-GCM",
        "aliases": {"AES-192-GCM", "A192GCM", "AES192GCM"},
        "category": "symmetric_encryption",
        "library": "unknown",
        "api_patterns": ("AES.new", "Cipher(algorithms.AES", "createCipheriv", "Cipher.getInstance(\"AES/GCM"),
        "quantum_status": "relatively_resistant",
        "risk_default": "LOW",
        "pqc_recommendation": "Monitor key management and preferred modes; continue to validate scheme assumptions.",
    },
    "AES-256-GCM": {
        "algorithm": "AES",
        "canonical_name": "AES-256-GCM",
        "aliases": {"AES-256-GCM", "A256GCM", "AES256GCM", "A256CBC"},
        "category": "symmetric_encryption",
        "library": "unknown",
        "api_patterns": ("AES.new", "Cipher(algorithms.AES", "createCipheriv", "Cipher.getInstance(\"AES/GCM"),
        "quantum_status": "relatively_resistant",
        "risk_default": "LOW",
        "pqc_recommendation": "Monitor key management and preferred modes; continue to validate scheme assumptions.",
    },
    "AES-128-CBC": {
        "algorithm": "AES",
        "canonical_name": "AES-128-CBC",
        "aliases": {"AES-128-CBC", "A128CBC"},
        "category": "symmetric_encryption",
        "library": "unknown",
        "api_patterns": ("AES.new", "Cipher(algorithms.AES", "createCipheriv", "Cipher.getInstance(\"AES/CBC"),
        "quantum_status": "relatively_resistant",
        "risk_default": "MEDIUM",
        "pqc_recommendation": "Review whether the mode and key length still fit the current security posture.",
    },
    "AES-256-CBC": {
        "algorithm": "AES",
        "canonical_name": "AES-256-CBC",
        "aliases": {"AES-256-CBC", "A256CBC"},
        "category": "symmetric_encryption",
        "library": "unknown",
        "api_patterns": ("AES.new", "Cipher(algorithms.AES", "createCipheriv", "Cipher.getInstance(\"AES/CBC"),
        "quantum_status": "relatively_resistant",
        "risk_default": "LOW",
        "pqc_recommendation": "Review whether the mode and key length still fit the current security posture.",
    },
    "SHA-256": {
        "algorithm": "SHA-256",
        "canonical_name": "SHA-256",
        "aliases": {"SHA-256", "SHA256", "sha256", "SHA_256"},
        "category": "hashing",
        "library": "hashlib",
        "api_patterns": ("hashlib.sha256", "createHash(\"sha256\")", "MessageDigest.getInstance(\"SHA-256\")", "SHA256withRSA"),
        "quantum_status": "lower_concern",
        "risk_default": "LOW",
        "pqc_recommendation": "Continue checking that the hash is not used as a password hash or legacy integrity primitive.",
    },
    "SHA-384": {
        "algorithm": "SHA-384",
        "canonical_name": "SHA-384",
        "aliases": {"SHA-384", "SHA384"},
        "category": "hashing",
        "library": "hashlib",
        "api_patterns": ("hashlib.sha384", "createHash(\"sha384\")"),
        "quantum_status": "lower_concern",
        "risk_default": "LOW",
        "pqc_recommendation": "Review whether a stronger or more modern integrity mechanism is needed in the protocol.",
    },
    "SHA-512": {
        "algorithm": "SHA-512",
        "canonical_name": "SHA-512",
        "aliases": {"SHA-512", "SHA512"},
        "category": "hashing",
        "library": "hashlib",
        "api_patterns": ("hashlib.sha512", "createHash(\"sha512\")", "MessageDigest.getInstance(\"SHA-512\")"),
        "quantum_status": "lower_concern",
        "risk_default": "LOW",
        "pqc_recommendation": "Review whether a stronger or more modern integrity mechanism is needed in the protocol.",
    },
    "HMAC-SHA256": {
        "algorithm": "HMAC",
        "canonical_name": "HMAC-SHA256",
        "aliases": {"HS256", "HMAC-SHA256", "HMACSHA256"},
        "category": "authentication",
        "library": "unknown",
        "api_patterns": ("createHmac(\"sha256\")", "Hmac.new", "HS256"),
        "quantum_status": "lower_concern",
        "risk_default": "MEDIUM",
        "pqc_recommendation": "Assess whether the token/JWT or MAC use is in scope for a PQC migration.",
    },
    "RSA-SHA256": {
        "algorithm": "RSA",
        "canonical_name": "RSA-SHA256",
        "aliases": {"RS256", "RSA-SHA256", "SHA256withRSA"},
        "category": "digital_signature",
        "library": "unknown",
        "api_patterns": ("RS256", "Signature.getInstance(\"SHA256withRSA\")", "rsa.sign", "rsa.generate_private_key"),
        "quantum_status": "vulnerable",
        "risk_default": "HIGH",
        "pqc_recommendation": "Migrate to ML-DSA or a signature scheme selected for your protocol and compatibility profile.",
    },
    "ECDSA-SHA256": {
        "algorithm": "ECDSA",
        "canonical_name": "ECDSA-SHA256",
        "aliases": {"ES256", "ECDSA-SHA256", "SHA256withECDSA"},
        "category": "digital_signature",
        "library": "unknown",
        "api_patterns": ("ES256", "ec.generate_private_key", "ec.ECDSA", "Signature.getInstance(\"SHA256withECDSA\")"),
        "quantum_status": "vulnerable",
        "risk_default": "HIGH",
        "pqc_recommendation": "Migrate to ML-DSA or an approved post-quantum signature scheme for the controlling protocol.",
    },
    "PBKDF2": {
        "algorithm": "PBKDF2",
        "canonical_name": "PBKDF2",
        "aliases": {"PBKDF2", "PBKDF2HMAC"},
        "category": "password_derivation",
        "library": "unknown",
        "api_patterns": ("PBKDF2HMAC", "hashes.PBKDF2HMAC", "kdf"),
        "quantum_status": "not_directly_quantum_vulnerable",
        "risk_default": "LOW",
        "pqc_recommendation": "Confirm the password derivation settings match current policy and consider hybrid approaches where required.",
    },
    "ECDH": {
        "algorithm": "ECDH",
        "canonical_name": "ECDH",
        "aliases": {"ECDH", "ecdh", "ECDH-256", "P-256"},
        "category": "key_exchange",
        "library": "unknown",
        "api_patterns": ("ec.generate_private_key", "ecdh.exchange", "KeyAgreement.getInstance", "ec.ECDH"),
        "quantum_status": "vulnerable",
        "risk_default": "HIGH",
        "pqc_recommendation": "Evaluate ML-KEM or a protocol-specific post-quantum key-establishment strategy.",
    },
    "RSA": {
        "algorithm": "RSA",
        "canonical_name": "RSA",
        "aliases": {"RSA", "rsa"},
        "category": "asymmetric",
        "library": "unknown",
        "api_patterns": ("rsa.generate_private_key", "RSA.generate", "KeyPairGenerator.getInstance(\"RSA\")", "KeyPairGenerator.getInstance(\"RSA\")"),
        "quantum_status": "vulnerable",
        "risk_default": "HIGH",
        "pqc_recommendation": "Evaluate a post-quantum signature or key-establishment mechanism appropriate for the use case.",
    },
    "ECDSA": {
        "algorithm": "ECDSA",
        "canonical_name": "ECDSA",
        "aliases": {"ECDSA", "ecdsa"},
        "category": "digital_signature",
        "library": "unknown",
        "api_patterns": ("ec.generate_private_key", "ec.ECDSA", "Signature.getInstance(\"SHA256withECDSA\")"),
        "quantum_status": "vulnerable",
        "risk_default": "HIGH",
        "pqc_recommendation": "Adopt a post-quantum signature scheme appropriate for the signing workflow.",
    },
    "AES": {
        "algorithm": "AES",
        "canonical_name": "AES",
        "aliases": {"AES", "aes"},
        "category": "symmetric_encryption",
        "library": "unknown",
        "api_patterns": ("AES.new", "algorithms.AES", "createCipheriv", "Cipher.getInstance(\"AES"),
        "quantum_status": "relatively_resistant",
        "risk_default": "MEDIUM",
        "pqc_recommendation": "Continue monitoring key management and mode choices and keep the algorithm inventory current.",
    },
    "SHA": {
        "algorithm": "SHA",
        "canonical_name": "SHA",
        "aliases": {"SHA", "sha"},
        "category": "hashing",
        "library": "unknown",
        "api_patterns": ("hashlib.sha", "createHash", "MessageDigest.getInstance(\"SHA"),
        "quantum_status": "lower_concern",
        "risk_default": "LOW",
        "pqc_recommendation": "Keep hash usage under review and prefer modern digest choices where protocol standards allow.",
    },
}
